

#%%%%%%%%%%%
#Blog Theme
#%%%%%%%%%%%
title: Sini Han's First Blog #博客标题
description: Wine's Story and personal Diary #博客描述
keywords: blog,css,html,php #博客关键字
author: "Sini Han"

#title hide and show
hide: What?
show: My git Story


#%%%%%%%%%%%
#URL Optionas
#%%%%%%%%%%%

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "sini1919.github.io" # change this to the base hostname & protocol for your site
#url: http://localhost:4000  #
buildtime: "1514736000" #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.


#%%%%%%%%%%%
#Base Settings
#%%%%%%%%%%%

#PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）
PJAX: true # Instant Note 1 (如不用评论系统建议开启)

paginate: 5      #The maximum number of articles displayed on the front banner
paginate_path: "page:num"

background: https://api.dujin.org/bing/1920.php # Top banner picture path ( Want to change it with my own picture, cna I?)
theme_color: 80020 #546E7A

google_analytics:
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

#MathJax switch
MathJax: false

#install emoji
plugins:
  - jemoji

# social account
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
